{% set name = "chiral-transfermatrix" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/chiral_transfermatrix-{{ version }}.tar.gz
  sha256: d29f5625781c7da173d55fdda5e207c7d024af2dc317d0e66888014d60f17c75

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - flit-core >=3.2,<4
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=1.15

test:
  imports:
    - chiral_transfermatrix
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: chiral-transfermatrix is a transfer/scattering matrix package for calculating the optical response of achiral and chiral multilayer structures.
  license: MIT
  license_file: LICENSE
  home: https://github.com/jfeist/chiral-transfermatrix

extra:
  recipe-maintainers:
    - jfeist
